import { NextResponse } from "next/server"
import nodemailer from "nodemailer"

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { to, userName, userRole, result } = body

    if (!to || !result) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    })

    // const severityEmoji =
    //   result.severity === "High"
    //     ? "🔴"
    //     : result.severity === "Moderate"
    //       ? "🟠"
    //       : result.severity === "Low to Moderate"
    //         ? "🟡"
    //         : "🟢"

    const preventiveMeasuresHTML = result.preventiveMeasures
      .map(
        (measure: string, i: number) =>
          `<tr><td style="padding:8px 12px;color:#0ea5e9;font-weight:bold;vertical-align:top;width:30px;">${i + 1}.</td><td style="padding:8px 12px;color:#334155;">${measure}</td></tr>`
      )
      .join("")

    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="margin:0;padding:0;background-color:#f1f5f9;font-family:Arial,sans-serif;">
      <div style="max-width:600px;margin:40px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 6px rgba(0,0,0,0.1);">
        
        <!-- Header -->
        <div style="background:#0ea5e9;padding:30px;text-align:center;">
          <h1 style="color:#ffffff;margin:0;font-size:24px;">BrainAI</h1>
          <p style="color:#e0f2fe;margin:8px 0 0;font-size:14px;">Brain Tumour Detection & Analysis Report</p>
        </div>

        <!-- Body -->
        <div style="padding:30px;">
          <p style="color:#334155;font-size:14px;line-height:1.6;">
            Dear <strong>${userName || "User"}</strong>,
          </p>
          <p style="color:#334155;font-size:14px;line-height:1.6;">
            Your MRI scan analysis is complete. Below are the findings:
          </p>

          <!-- Diagnosis Card -->
          <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:20px;margin:20px 0;">
            <h2 style="color:#0ea5e9;margin:0 0 16px;font-size:18px;">Diagnosis Summary</h2>
            <table style="width:100%;border-collapse:collapse;">
              <tr>
                <td style="padding:6px 0;color:#64748b;font-size:13px;">Tumour Type:</td>
                <td style="padding:6px 0;color:#1e293b;font-size:13px;font-weight:bold;">${result.type}</td>
              </tr>
              <tr>
                <td style="padding:6px 0;color:#64748b;font-size:13px;">Confidence Score:</td>
                <td style="padding:6px 0;color:#1e293b;font-size:13px;font-weight:bold;">${result.confidence}%</td>
              </tr>
            
              <tr>
                <td style="padding:6px 0;color:#64748b;font-size:13px;">Role:</td>
                <td style="padding:6px 0;color:#1e293b;font-size:13px;">${userRole === "doctor" ? "Doctor / Lab" : "Patient"}</td>
              </tr>
              <tr>
                <td style="padding:6px 0;color:#64748b;font-size:13px;">Date:</td>
                <td style="padding:6px 0;color:#1e293b;font-size:13px;">${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</td>
              </tr>
            </table>
          </div>

          <!-- Description -->
          <p style="color:#334155;font-size:14px;line-height:1.6;">${result.description}</p>

          <!-- Preventive Measures -->
          <h3 style="color:#0ea5e9;font-size:16px;margin:24px 0 12px;">Recommendations</h3>
          <table style="width:100%;border-collapse:collapse;background:#f8fafc;border-radius:8px;">
            ${preventiveMeasuresHTML}
          </table>

          <!-- Disclaimer -->
          <div style="margin-top:30px;padding:16px;background:#fef2f2;border-radius:8px;border:1px solid #fecaca;">
            <p style="color:#991b1b;font-size:11px;margin:0;line-height:1.5;">
              <strong>Disclaimer:</strong> This report is generated by an AI model for educational and research purposes only. 
              It should not be used as a substitute for professional medical advice. Always consult a qualified healthcare provider.
            </p>
          </div>
        </div>

        <!-- Footer -->
        <div style="background:#f1f5f9;padding:20px;text-align:center;border-top:1px solid #e2e8f0;">
          <p style="color:#94a3b8;font-size:12px;margin:0;">Generated by BrainAI - Brain Tumour Detection & Analysis Platform</p>
        </div>
      </div>
    </body>
    </html>
    `

    await transporter.sendMail({
      from: `"BrainAI" <${process.env.GMAIL_USER}>`,
      to,
      subject: `BrainAI Report: ${result.type} - Confidence ${result.confidence}%`,
      html: htmlContent,
    })

    return NextResponse.json({ success: true, message: "Report sent successfully" })
  } catch (error) {
    console.error("Email send error:", error)
    return NextResponse.json(
      { error: "Failed to send email. Check server logs." },
      { status: 500 }
    )
  }
}
